### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [zosiasz/Grunt#1]
dorzucilem zmiane z usunieciem foldero repo
- [x] dodaj plik `.gitignore`, ktory bedzie ignorowal zmiany w katalogu `node_modules/`
- [x] jak chce odpalic w terminalu task `grunt` to nie dziala - sprawdz prosze dlaczego
- [ ] dodaj jakis zupelnie najprostszy plik html, ktory bedzie wykorzystywal wygenerowany css i wygenerowany obrazek (obrazek tez prosze abys dodala)

**Comment by zdolny** [comment]
to pozostal tylko punkt 3 z checklisty pliz
